name: Cache
  uses:

  with:
    # A list of files, directories, and wildcard patterns to cache and restore
    path: 
    # An explicit key for restoring and saving the cache
    key: 
    # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
    restore-keys: # optional
on:
  push:
    branches:
    - main
    - release/*
      on:
  pull_request:
    branches:
    - main
      on:
  schedule:
  - cron: "0 2 * * 1-5"
